### ISSUE TITLE
is version.sbt required?

### ISSUE THREAD

**Issue by indusbull** [limansky/sbt-git-flow-version#2]
Hi 

Thanks for sharing the plugin. I am going through the same pains with git flow and sbt. This plugin seems to be perfect solution.

I just have one question. I added this plugin to plugins.sbt in my feature branch - "foobar". Then removed "version" var from my build.sbt.  Now when I package my app, it generates jar with following name and version - myapp_2.12-1.0.0-foobar-SNAPSHOT.jar.  My question is from where does it pick up version - "1.0.0" first time. Since its existing app, I don't want to start from 1.0.0. Do I need to maintain version.sbt at root of my project? 

Thanks again!

**Comment by limansky** [comment]
Hi,

  You shouldn't use version.sbt because once you define `version` in your build the plugin will not work (because settings from the project definition has higher priority than settings defined in plugins). The initial version defined via setting called `initialVersion`. You can defined it in your build.sbt.

**Comment by indusbull** [comment]
That solves the problem. Thank you!!
